---
- name: Add MySQL Repo (RedHat)
  become: true
  yum:
    name: '{{ mysql_installers_path_on_target }}/{{ mysql_installer_filename }}'
    state: present

- name: Install MySQL (RedHat)
  become: true
  yum:
    name: mysql-community-server
    state: installed

- name: Ensure MySQL service is started (RedHat)
  become: true
  service:
    name: '{{ mysql_service_name }}'
    state: started
    enabled: true
